service: localstack-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    entpointFile: localstack_endpoints.json

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  createUser:
    handler: src/lambda/CreateUser.handler
    events:
      - http:
          path: serverlessSetup/user
          method: post
  updateUser:
    handler: src/lambda/UpdateUser.handler
    events:
      - http:
          path: serverlessSetup/user
          method: put
